<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Contasapagar extends CI_Controller{
    function __construct()
    {
        parent::__construct();

        if( (!session_id()) || (!$this->session->userdata('logado'))){
            redirect('dashboard/index');
}
        $this->load->model('Contasapagar_model');
    }

function index(){

  $data['contasapagar']=$this->Contasapagar_model->getallcontasapagar();
  $this->load->view('include/header');
  $this->load->view('contasapagar/index',$data);
  $this->load->view('include/footer');
}


function add(){

$valor= str_replace("," , "." ,$this->input->post('valor'));
  $params = array(
      'descricao'=>$this->input->post('descricao'),
      'valor'=>$valor,
      'numerodoc'=>$this->input->post('numero'),
      'datavenc'=>$this->input->post('vencimento')

  );


    $null=$this->Contasapagar_model->add($params);

    redirect('contasapagar/index');
}

function recebeconta($id){

$valorpago = str_replace("," , "." ,$this->input->post('valorpago'));
  $params = array(
    'forma_pgtonome'=>$this->input->post('formarecebimento'),
      'datapgto'=>$this->input->post('datapgto'),
      'valorpgto'=> $valorpago,

  );

  $null = $this->Contasapagar_model->receberconta($id,$params);


  $tipomov='2';
  $descricao = "PAGAMENTO REF ". $this->input->post('descricaoconta');
    $fluxo = array(
        'forma'=> $this->input->post('formarecebimento'),
        'data'=>$this->input->post('datapgto'),
        'valor'=>$valorpago,
        'descricao'=>$descricao,
        'tipomov'=>$tipomov
    );

  $this->load->model('Fluxo_model');
    $this->Fluxo_model->add($fluxo);

  redirect('contasapagar/index');

}


  }
