<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Painel extends CI_Controller{
    function __construct()
    {
        parent::__construct();

        if( (!session_id()) || (!$this->session->userdata('logado'))){
            redirect('dashboard/index');
}

}

function index(){


        $this->load->view('include/header');
        
        $this->load->view('include/footer');
}
}
