<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Pdv extends CI_Controller{
    function __construct()
    {
        parent::__construct();



        $this->load->model('Pdv_model');
    }


function index(){

  date_default_timezone_set('America/Sao_Paulo');
  $data = date('d/m/Y');
  $hora = date('H:i');
$params = array(
      'data'=>$data,
      'hora'=>$hora

);
  $pedido = $this->Pdv_model->novavenda($params);




    redirect('pdv/editapdv/'.$pedido);

}


public function desconto(){

  $idpdv =$this->input->post('idpdv');
  $valordesconto = $this->input->post('valordesconto');

      if($this->Pdv_model->desconto($idpdv,$valordesconto)==TRUE){
        echo json_encode(array('result'=> true));
      }

}

public function editapdv($pedido){

  $data['pdv']= $this->Pdv_model->getvenda($pedido);
$data['itenspdv']= $this->Pdv_model->getitens($pedido);
$data['totalitens'] = $this->Pdv_model->totalpedido($pedido);
$data['pagamento'] = $this->Pdv_model->getpagamento($pedido);

  $this->load->view('include/header');
  $this->load->view('pdv/pdv',$data);
  $this->load->view('include/footer');


}

public function pagamento(){

  $tipomov="1";

  date_default_timezone_set('America/Sao_Paulo');
  $data = date('d/m/Y');
  $idpedido = $this->input->post('idpdv');

  $descricao= 'PAGAMENTO VENDA PDV Nº - '.$idpedido;
    $valorrecebido = $this->input->post('valorrecebido');
    $totalvenda = $this->input->post('totalvendapdv');
    $restante =$this->input->post('restante');
    $valorjarecebido = $this->input->post('valorjarecebido');
    $valordescontovenda = $this->input->post('valordescontovenda');
     $verificapgto = ($valordescontovenda + $valorjarecebido + $valorrecebido);


if($restante>$valorrecebido){

  $params = array(

    'valor' => $this->input->post('valorrecebido'),
    'idpdv' => $this->input->post('idpdv'),
    'nomerecebimento' => $this->input->post('formarecebimento')
  );


$null=$this->Pdv_model->pagamento($params);



      $fluxo = array(
      		'valor'=>$this->input->post('valorrecebido'),
      		'forma'=> $this->input->post('formarecebimento'),
      		'tipomov'=>$tipomov,
      		'descricao'=> $descricao,

      		'data'=>$data
      );

      $this->load->model('Fluxo_model');
      $null=	$this->Fluxo_model->add($fluxo);

      echo json_encode(array('result'=> false));
    }if ($restante<=$valorrecebido){

      $params = array(

        'valor' => $restante,
        'idpdv' => $this->input->post('idpdv'),
        'nomerecebimento' => $this->input->post('formarecebimento')
      );


    $null=$this->Pdv_model->pagamento($params);

      $fluxo = array(
          'valor'=>$restante,
          'forma'=> $this->input->post('formarecebimento'),
          'tipomov'=>$tipomov,
          'descricao'=> $descricao,

          'data'=>$data
      );
      $this->load->model('Fluxo_model');
      $null=	$this->Fluxo_model->add($fluxo);

            echo json_encode(array('result'=> true));
    }





}

public function excluiritem(){

  $id = $this->input->post('id');
  if($this->Pdv_model->excluiritem($id)== true){

    echo json_encode(array('result'=> true));

  }
  else{
        echo json_encode(array('result'=> false));
    }

}

function buscapdv(){
$produto =$this->input->post('produto');
  if($array =$this->Pdv_model->buscaproduto($produto)){
    echo json_encode(array('result'=> true));

  }
  else{
    echo json_encode(array('result'=> false));
  }
}


public function additem(){

$pedido = $this->input->post('idpdv');
  $params = array(
    'nomeproduto' =>$this->input->post('nomeproduto'),
    'valor'=> $this->input->post('venda'),
    'idproduto'=> $this->input->post('idproduto'),
    'qtdd' => $this->input->post('quantidade'),
      'codbarra' => $this->input->post('codbarra'),
    'idpdv'=>$this->input->post('idpdv')

  );

$null=$this->Pdv_model->additem($params);


echo json_encode(array('result'=> true));


}


  }
