<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Pdv extends CI_Controller{
    function __construct()
    {
        parent::__construct();



        $this->load->model('Pdv_model');
    }


function index(){

  date_default_timezone_set('America/Sao_Paulo');
  $data = date('d/m/Y');
  $hora = date('H:i');
$params = array(
      'data'=>$data,
      'hora'=>$hora

);
  $pedido = $this->Pdv_model->novavenda($params);

<<<<<<< HEAD

    
    redirect('pdv/editapdv/'.$pedido);
  
}


public function desconto(){

  $idpdv =$this->input->post('idpdv');
  $valordesconto = $this->input->post('valordesconto');

      if($this->Pdv_model->desconto($idpdv,$valordesconto)==TRUE){
        echo json_encode(array('result'=> true));
      }

}

public function editapdv($pedido){

  $data['pdv']= $this->Pdv_model->getvenda($pedido);
$data['itenspdv']= $this->Pdv_model->getitens($pedido);
$data['totalitens'] = $this->Pdv_model->totalpedido($pedido);
$data['pagamento'] = $this->Pdv_model->getpagamento($pedido);

  $this->load->view('include/header');
  $this->load->view('pdv/pdv',$data);
  $this->load->view('include/footer');


}

public function pagamento(){

        $params = array(

          'valor' => $this->input->post('valorrecebido'),
          'idpdv' => $this->input->post('idpdv'),
          'nomerecebimento' => $this->input->post('formarecebimento')
        );

        if($this->Pdv_model->pagamento($params)!=null){
          echo json_encode(array('result'=> true));
        }
        else{
          echo json_encode(array('result'=> false));

        }

}

public function excluiritem(){

  $id = $this->input->post('id');
  if($this->Pdv_model->excluiritem($id)== true){

    echo json_encode(array('result'=> true));

  }
  else{
        echo json_encode(array('result'=> false));
    }
=======
  $this->$data['pdv']= $this->Pdv_model->getvenda($pedido);
$this->$data['itenspdv']= $this->Pdv_model->getitens($pedido);

  $this->load->view('include/header');
  $this->load->view('pdv/pdv',$this->$data);
  $this->load->view('include/footer');
>>>>>>> cd8a4d858b8346aab7ab79bdf49b3e42779118fe
}

function buscapdv(){
$produto =$this->input->post('produto');
  if($array =$this->Pdv_model->buscaproduto($produto)){
    echo json_encode(array('result'=> true));

  }
  else{
    echo json_encode(array('result'=> false));
  }
}

<<<<<<< HEAD
public function additem(){
=======
public function additem($id){
>>>>>>> cd8a4d858b8346aab7ab79bdf49b3e42779118fe
$pedido = $this->input->post('idpdv');
  $params = array(
    'nomeproduto' =>$this->input->post('nomeproduto'),
    'valor'=> $this->input->post('venda'),
    'idproduto'=> $this->input->post('idproduto'),
    'qtdd' => $this->input->post('quantidade'),
    'idpdv'=>$this->input->post('idpdv')

  );

$null=$this->Pdv_model->additem($params);

<<<<<<< HEAD
echo json_encode(array('result'=> true));
=======

$this->$data['pdv']= $this->Pdv_model->getvenda($pedido);
$this->$data['itenspdv']= $this->Pdv_model->getitens($pedido);

$this->load->view('include/header');
$this->load->view('pdv/pdv',$this->$data);
$this->load->view('include/footer');
>>>>>>> cd8a4d858b8346aab7ab79bdf49b3e42779118fe


}


  }
