<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Pdv extends CI_Controller{
    function __construct()
    {
        parent::__construct();



        $this->load->model('Pdv_model');
    }


function index(){

  date_default_timezone_set('America/Sao_Paulo');
  $data = date('d/m/Y');
  $hora = date('H:i');
$params = array(
      'data'=>$data,
      'hora'=>$hora

);
  $pedido = $this->Pdv_model->novavenda($params);

  $this->$data['pdv']= $this->Pdv_model->getvenda($pedido);
$this->$data['itenspdv']= $this->Pdv_model->getitens($pedido);

  $this->load->view('include/header');
  $this->load->view('pdv/pdv',$this->$data);
  $this->load->view('include/footer');
}

function buscapdv(){
$produto =$this->input->post('produto');
  if($array =$this->Pdv_model->buscaproduto($produto)){
    echo json_encode(array('result'=> true));

  }
  else{
    echo json_encode(array('result'=> false));
  }
}

public function additem($id){
$pedido = $this->input->post('idpdv');
  $params = array(
    'nomeproduto' =>$this->input->post('nomeproduto'),
    'valor'=> $this->input->post('venda'),
    'idproduto'=> $this->input->post('idproduto'),
    'qtdd' => $this->input->post('quantidade'),
    'idpdv'=>$this->input->post('idpdv')

  );

$null=$this->Pdv_model->additem($params);


$this->$data['pdv']= $this->Pdv_model->getvenda($pedido);
$this->$data['itenspdv']= $this->Pdv_model->getitens($pedido);

$this->load->view('include/header');
$this->load->view('pdv/pdv',$this->$data);
$this->load->view('include/footer');


}


  }
