<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Permissoes extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();

        if ((!session_id()) || (!$this->session->userdata('logado'))) {
            redirect('dashboard/index');
        }



        $this->load->helper(array('form', 'codegen_helper'));
        $this->load->model('Permissoes_model', '', true);
        $this->data['menuConfiguracoes'] = 'Permissões';
    }

    public function index()
    {
        $this->gerenciar();
    }


    public function gerenciar()
    {
        $data['permissao'] = $this->Permissoes_model->get_all_permissoes();

//    $data['_view'] = 'usuario/index';
        //  $this->load->view('layouts/main',$data);

        $this->load->view('include/header');
        $this->load->view('permissoes/index', $data);
        $this->load->view('include/footer');
    }

    public function add(){


      $this->load->library('form_validation');

  $this->form_validation->set_rules('nome','Nome','required');


  if($this->form_validation->run())
      {



      $nomePermissao = $this->input->post('nome');
      $situacao = $this->input->post('situacao');
      $permissoes = array(

              'aCliente' => $this->input->post('aCliente'),
              'eCliente' => $this->input->post('eCliente'),
              'dCliente' => $this->input->post('dCliente'),
              'vCliente' => $this->input->post('vCliente'),

              'aProduto' => $this->input->post('aProduto'),
              'eProduto' => $this->input->post('eProduto'),
              'dProduto' => $this->input->post('dProduto'),
              'vProduto' => $this->input->post('vProduto'),

              'aServico' => $this->input->post('aServico'),
              'eServico' => $this->input->post('eServico'),
              'dServico' => $this->input->post('dServico'),
              'vServico' => $this->input->post('vServico'),

              'aFunc' => $this->input->post('aFunc'),
              'eFunc' => $this->input->post('eFunc'),
              'dFunc' => $this->input->post('dFunc'),
              'vFunc' => $this->input->post('vFunc'),

              'vRel' => $this->input->post('vRel'),
              'relv' => $this->input->post('relv'),
              'relcli' => $this->input->post('relcli'),
              'relc' => $this->input->post('relc'),
              'relf' => $this->input->post('relf'),

              'aVenda' => $this->input->post('aVenda'),
              'eVenda' => $this->input->post('eVenda'),
              'dVenda' => $this->input->post('dVenda'),
              'vVenda' => $this->input->post('vVenda'),

              'aAgenda' => $this->input->post('aAgenda'),
              'eAgenda' => $this->input->post('eAgenda'),
              'dAgenda' => $this->input->post('dAgenda'),
              'vAgenda' => $this->input->post('vAgenda'),

              'aCategoria' => $this->input->post('aCategoria'),
              'eCategoria' => $this->input->post('eCategoria'),
              'dCategoria' => $this->input->post('dCategoria'),
              'vCategoria' => $this->input->post('vCategoria'),

              'aPermissao'=> $this->input->post('aPermissao'),
              'vPermissao' => $this->input->post('vPermissao'),
              'ePermissao'=> $this->input->post('ePermissao'),
              'dPermissao'=> $this->input->post('dPermissao'),

              'aPagar' => $this->input->post('aPagar'),
              'ePagar' => $this->input->post('ePagar'),
              'dPagar' => $this->input->post('dPagar'),
              'vPagar' => $this->input->post('vPagar'),

              'aReceber' => $this->input->post('aReceber'),
              'eReceber' => $this->input->post('eReceber'),
              'dReceber' => $this->input->post('dReceber'),
              'vReceber' => $this->input->post('vReceber'),

              'vUser' => $this->input->post('vUser'),
              'aUser' => $this->input->post('aUser'),
              'eUser' => $this->input->post('eUser'),
              'dUser' => $this->input->post('dUser'),

              'vConfig' => $this->input->post('vConfig'),

              'cPermissao' => $this->input->post('cPermissao'),
              'cBackup' => $this->input->post('cBackup'),



        );
      $permissoes = serialize($permissoes);

      $data = array(
            'nome' => $nomePermissao,
            'permissoes' => $permissoes,
            'situacao' => $situacao
        );


        if ($this->Permissoes_model->add($data) == true) {
            $this->session->set_flashdata('success', 'Permissão editada com sucesso!');
            redirect('permissoes/index');
        } else {
            $this->data['custom_error'] = '<div class="form_error"><p>Ocorreu um errro.</p></div>';
        }

}


        $this->load->view('include/header');
        $this->load->view('permissoes/add');
        $this->load->view('include/footer');

    }


    public function edit($id)
    {
        $this->data['result'] = $this->Permissoes_model->getById($id);

        $this->load->view('include/header');
        $this->load->view('permissoes/edit', $this->data);
        $this->load->view('include/footer');
    }




    public function update()
    {
        $nomePermissao = $this->input->post('nome');
        $situacao = $this->input->post('situacao');
        $permissoes = array(

                'aCliente' => $this->input->post('aCliente'),
                'eCliente' => $this->input->post('eCliente'),
                'dCliente' => $this->input->post('dCliente'),
                'vCliente' => $this->input->post('vCliente'),

                'aProduto' => $this->input->post('aProduto'),
                'eProduto' => $this->input->post('eProduto'),
                'dProduto' => $this->input->post('dProduto'),
                'vProduto' => $this->input->post('vProduto'),

                'aServico' => $this->input->post('aServico'),
                'eServico' => $this->input->post('eServico'),
                'dServico' => $this->input->post('dServico'),
                'vServico' => $this->input->post('vServico'),

                'aFunc' => $this->input->post('aFunc'),
                'eFunc' => $this->input->post('eFunc'),
                'dFunc' => $this->input->post('dFunc'),
                'vFunc' => $this->input->post('vFunc'),

                'vRel' => $this->input->post('vRel'),
                'relv' => $this->input->post('relv'),
                'relcli' => $this->input->post('relcli'),
                'relc' => $this->input->post('relc'),
                'relf' => $this->input->post('relf'),

                'aVenda' => $this->input->post('aVenda'),
                'eVenda' => $this->input->post('eVenda'),
                'dVenda' => $this->input->post('dVenda'),
                'vVenda' => $this->input->post('vVenda'),

                'aAgenda' => $this->input->post('aAgenda'),
                'eAgenda' => $this->input->post('eAgenda'),
                'dAgenda' => $this->input->post('dAgenda'),
                'vAgenda' => $this->input->post('vAgenda'),

                'aCategoria' => $this->input->post('aCategoria'),
                'eCategoria' => $this->input->post('eCategoria'),
                'dCategoria' => $this->input->post('dCategoria'),
                'vCategoria' => $this->input->post('vCategoria'),

                'aPermissao'=> $this->input->post('aPermissao'),
                'vPermissao' => $this->input->post('vPermissao'),
                'ePermissao'=> $this->input->post('ePermissao'),
                'dPermissao'=> $this->input->post('dPermissao'),

                'aPagar' => $this->input->post('aPagar'),
                'ePagar' => $this->input->post('ePagar'),
                'dPagar' => $this->input->post('dPagar'),
                'vPagar' => $this->input->post('vPagar'),

                'aReceber' => $this->input->post('aReceber'),
                'eReceber' => $this->input->post('eReceber'),
                'dReceber' => $this->input->post('dReceber'),
                'vReceber' => $this->input->post('vReceber'),

                'vUser' => $this->input->post('vUser'),
                'aUser' => $this->input->post('aUser'),
                'eUser' => $this->input->post('eUser'),
                'dUser' => $this->input->post('dUser'),

                'vConfig' => $this->input->post('vConfig'),

                'cPermissao' => $this->input->post('cPermissao'),
                'cBackup' => $this->input->post('cBackup'),



          );
        $permissoes = serialize($permissoes);

        $data = array(
              'nome' => $nomePermissao,
              'permissoes' => $permissoes,
              'situacao' => $situacao
          );

        if ($this->Permissoes_model->update('permissoes', $data, 'idPermissao', $this->input->post('idPermissao')) == true) {
            $this->session->set_flashdata('success', 'Permissão editada com sucesso!');
            redirect(base_url() . 'permissoes/edit/'.$this->input->post('idPermissao'));
        } else {
            $this->data['custom_error'] = '<div class="form_error"><p>Ocorreu um errro.</p></div>';
        }



        $this->data['result'] = $this->Permissoes_model->get_permissao($id);

        $this->load->view('include/header');
        $this->load->view('permissoes/edit', $this->data);
        $this->load->view('include/footer');
    }
}
