<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Adicionais_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }


    function add($params)
    {
        $this->db->insert('adicionais',$params);
        return $this->db->insert_id();
    }

    function get_all(){
      $this->db->order_by('id', 'desc');
      return $this->db->get('adicionais')->result_array();
    }

}
