<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Configuracoes_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
  }

  public function get_empresa(){

    return $this->db->get('empresa')->row_array();

  }

  public function update_empresa($id,$params){
    $this->db->where('id',$id);
     $this->db->update('empresa',$params);
     if ($this->db->affected_rows() == '1')
    {
    return TRUE;
    }

    return FALSE;

  }

  public function addimpressora($params){
    $this->db->insert('impressoras',$params);
    if ($this->db->affected_rows() == '1')
   {
   return TRUE;
   }

   return FALSE;

  }

  public function getimprede(){
    $this->db->select('impressora');
   $this->db->from('impressoras');
   $this->db->where('localimpressao', '1');

    return $this->db->get()->result();
  }

  }
