<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Inventario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
function novoinventario($data)
{
    $this->db->insert('inventario',$data);
    return $this->db->insert_id();
}

function getinventario($idinv){

  return $this->db->get_where('inventario',array('id'=>$idinv))->row_array();
}

function itensinv($params){

  $this->db->insert('itensinventario',$params);
  return $this->db->insert_id();

}

function getallinv(){

  $this->db->order_by('id', 'DESC');
  return $this->db->get('inventario')->result_array();

}
function atualizaestoque($idproduto,$qtdd){


  $this->db->set('estoque',$qtdd);
  $this->db->where('id',$idproduto);
   $this->db->update('produto');
   if ($this->db->affected_rows() == '1')
{
  return TRUE;
}

return FALSE;
}
function getitens($idinv){

  $this->db->select('*');
 $this->db->from('itensinventario');
 $this->db->where('idinvent', $idinv);

  return $this->db->get()->result_array();
}

}
