<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Usuario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get usuario by idusuario
     */
    function get_usuario($idusuario)
    {
        return $this->db->get_where('usuario',array('idusuario'=>$idusuario))->row_array();
    }
        
    /*
     * Get all usuarios
     */
    function get_all_usuarios()
    {
        $this->db->order_by('idusuario', 'desc');
        return $this->db->get('usuario')->result_array();
    }
        
    /*
     * function to add new usuario
     */
    function add_usuario($params)
    {
        $this->db->insert('usuario',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update usuario
     */
    function update_usuario($idusuario,$params)
    {
        $this->db->where('idusuario',$idusuario);
        return $this->db->update('usuario',$params);
    }
    
    /*
     * function to delete usuario
     */
    function delete_usuario($idusuario)
    {
        return $this->db->delete('usuario',array('idusuario'=>$idusuario));
    }
}
